version: '3.7'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ../frontend:/app
    stdin_open: true

  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ../nginx
    ports:
      - "3000:80"

  backend:
    build: 
      dockerfile: Dockerfile.dev
      context: ../server
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ../server:/app

  mysql:
    build: ../mysql
    restart: unless-stopped
    container_name: app_mysql
    ports:
      - "3306:3306"
    volumes:
      - ../mysql/mysql_data:/var/lib/mysql
      - ../mysql/sql/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=tiger
      - MYSQL_DATABASE=myapp